### PR TITLE
Adding a Django development environment

### LINKED ISSUE #6: Setting up a Django development environment
we need to add Django development environment so we will be able to write our web application.

### PR DESCRIPTION
**Pull request by shakedch**
- Setup Pipenv to install and manage Django and other Python dependencies
- Bootstrapped an empty Django application

**Note:** 
[1]The changes had been auto-generated.
[2] Automating our environment and editing Vagrantfile and bootstrap.sh were not performed yet and will be performed by another team member.

Fixes: #6

### CODE REVIEW

**Comment by ifireball** [comment]
Generally a good PR description, but If you don't have a Vagrantfile, wouldn't you say that saying what `vagrant up` will do is a little misleading?

Also I don't see a linked issue

**Comment by shakedch** [comment]
An issue has been opened but I couldn't link this PR to it .
In my opinion I don't have permissions.

**Comment by ifireball** [comment]
You can mention the issue in the commit message and PR description like this: Fixes: #6

**Comment by shakedch** [comment]
Thank you!

**Comment by ifireball** [comment]
The part about the HTTP access is not very accurate as well right? Please make sure your PR description accurately describes the change you are making.

**Comment by shakedch** [comment]
Does the description match now?

**Comment by ifireball** [comment]
yes, but now that I look at the files - I see you have an unnecessary `jobboard` directory and all the python files are in it. You probably want to make it so `manage.py` is at the root of the repository - it will make it easier to work with it. 

It seems you've forgot to add the `.` parameter to `django-admin` like I explained on page 29 of the excercise.

**Comment by ifireball** [comment]
did you regenerate the files with django or did you just move them manually? IIRC the `__init__.py`, `settings.py` and `wsgi.py` do need to be in a directory...

**Comment by shakedch** [comment]
I did it manually, Is the directory necessary? Do I need to transfer the 3 files you specified to the directory?

**Comment by ifireball** [comment]
The directory structure is important, and moving the files manually may make Django not work. Please recreate the files properly from scratch with django-admin

**Comment by shakedch** [comment]
I recreate the files properly from scratch with django-admin. This time I made sure that I have not forgot to add the . parameter to django-admin. The additional directory  created and all the python files are in it - like the first time.
In addition when I looked at previous repos for comparison(beyond_tutorial) I saw that the other students opened an additional directory with all the python files in it.

Am I missing something?

django admin

**Comment by ifireball** [comment]
The important part is that manage.py is at the root directory. Previously you had two directories - one with manage.py in it and another one inside it with the other files

**Comment by ifireball** [comment]
Anyway it looks better now

**Comment by shakedch** [comment]
Do I have to do something else before merging the PR?

**Comment by ifireball** [comment]
no, merging.

**Pull request merged**
