### PR TITLE
add email account to settings.py

### LINKED ISSUE #65: add mail account
Adding an email account to send alert emails to users

### PR DESCRIPTION
**Pull request by advapi**
add email account to settings.py and protect sensitive info with python decouple
fixes: #65

### CODE REVIEW

**Comment by advapi** [comment]
I've created .env file in my local repo so I guess that's the reason pytest fail here but the tests pass in my env.

**Comment by bardielle** [comment]
@advapi you're right- pytest fails because you're using the env var but didn't declare it
the logs: 
`decouple.UndefinedValueError: EMAIL_HOST_USER not found. Declare it as envvar or define a default value.`
So define a default value (for example "default_value"

**Comment by advapi** [comment]
@bardielle  fixed

**Comment by guy9050** [comment]
LGTM

**Pull request merged**
