### PR TITLE
Adding homepage to our website part1

### LINKED ISSUE #11: Add a homepage
Creating the relevant folders for uploading the homepage(not including uploading the .HTML file)

### PR DESCRIPTION
**Pull request by shakedch**
- Bootstrapping a Django app

- Registering our app with Django

- Create a directory for  the template

**Note:** 
[1]The changes had been auto-generated.
[2] Adding the FE of our homepage will be done by another team member.

Fixes: #11

### CODE REVIEW

**Comment by shakedch** [comment]
@ifireball @bardielle

**Comment by ifireball** [comment]
So was the code in this PR auto-generated?

Also you can't commit an empty directory to Git, so the 2rd line in the PR description is probably incorrect.

**Comment by shakedch** [comment]
Note about auto-generated files was added to description.

There is no empty directory, since there is an empty HTML file in it.

**Comment by shakedch** [comment]
@ifireball

**Comment by ifireball** [comment]
Please be more detailed and accurate in the future - the change in `settings.py` was not autogenerated. The point of the question about this was to know which files should I be looking at.

Merging for now, to let you move on.

**Pull request merged**
