### PR TITLE
Adding vagrantfile to create a Linux development environment

### PR DESCRIPTION
**Pull request by advapi**
Adding a Vagrantfile for spinning up a development VM
Vagrant is a tool for using virtual machines to share development environments.
Learn more about it at:
https://www.vagrantup.com/
Also adding `.gitignore` file to ignore so data that Vagrant
creates.
related issue : #2

### CODE REVIEW

**Comment by ifireball** [comment]
Generally looks ok, but I'd expect to only see a single commit in this PR. Could you try quashing all the commits together? This could be done with a `git rebase -i` command.

Also I'm not seeing a link to an issue

**Comment by advapi** [comment]
@ifireball In order to use the command you suggested, do I need to close this PR and open a new one?
also, there is a link to the issue- #2

**Comment by ifireball** [comment]
No you can use the command to modify your local branch, and then you can use `git push --force` (with the remote name and the branch name) to update the branch in your fork. That will also update the PR you made from it.

https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

You link issues to PRs in one of two ways:
1. Add to the list of linked issues on the left bar in the PR screen
2. Mention the issue number in the PR description like so: #2 
3. You can and should also mention issues in commit messages.

**Comment by advapi** [comment]
@ifireball  I think its ok now.

**Comment by ifireball** [comment]
It is. Merging.

**Pull request merged**
